---
# 1. Delete CR, CSV and Subscription
# -----------------------------------------------------------------------------
# IMO

- name: Get ibm-metrics-operator Subscription
  kubernetes.core.k8s_info:
    api_version: operators.coreos.com/v1alpha1
    kind: Subscription
    namespace: redhat-marketplace
    label_selectors:
      - "instance = imo"
  register: imo_subscription

- name: "uninstall : Delete the MarketplaceConfig"
  kubernetes.core.k8s:
    state: absent
    api_version: marketplace.redhat.com/v1alpha1
    kind: MarketplaceConfig
    namespace: redhat-marketplace
    name: marketplaceconfig
    wait: yes
    wait_timeout: 600
  when: (imo_subscription.resources is defined) and (imo_subscription.resources| length == 1)

- name: "uninstall : Delete the MeterBase"
  kubernetes.core.k8s:
    state: absent
    api_version: marketplace.redhat.com/v1alpha1
    kind: MeterBase
    namespace: redhat-marketplace
    name: rhm-marketplaceconfig-meterbase
    wait: yes
    wait_timeout: 600
  when: (imo_subscription.resources is defined) and (imo_subscription.resources| length == 1)

- name: "uninstall : Delete ibm-metrics-operator CSV"
  kubernetes.core.k8s:
    state: absent
    api_version: operators.coreos.com/v1alpha1
    kind: ClusterServiceVersion
    namespace: redhat-marketplace
    label_selectors:
      - "operators.coreos.com/ibm-metrics-operator.redhat-marketplace"
    wait: yes
    wait_timeout: 300
  when: (imo_subscription.resources is defined) and (imo_subscription.resources| length == 1)

- name: "uninstall : Delete ibm-metrics-operator Subscription"
  kubernetes.core.k8s:
    state: absent
    api_version: operators.coreos.com/v1alpha1
    kind: Subscription
    name: ibm-metrics-operator
    namespace: redhat-marketplace
    wait: yes
    wait_timeout: 300
  when: (imo_subscription.resources is defined) and (imo_subscription.resources| length == 1)

# DRO

- name: Get ibm-data-operator Subscription
  kubernetes.core.k8s_info:
    api_version: operators.coreos.com/v1alpha1
    kind: Subscription
    namespace: redhat-marketplace
    label_selectors:
      - "instance = dro"
  register: dro_subscription

- name: "uninstall : Delete the DataReporterConfig"
  kubernetes.core.k8s:
    state: absent
    api_version: marketplace.redhat.com/v1alpha1
    kind: DataReporterConfig
    namespace: redhat-marketplace
    name: datareporterconfig
    wait: yes
    wait_timeout: 600
  when: (dro_subscription.resources is defined) and (dro_subscription.resources| length == 1)


- name: "uninstall : Delete  ibm-data-reporter-operator CSV"
  kubernetes.core.k8s:
    state: absent
    api_version: operators.coreos.com/v1alpha1
    kind: ClusterServiceVersion
    namespace: redhat-marketplace
    label_selectors:
      - "operators.coreos.com/ibm-data-reporter-operator.redhat-marketplace"
    wait: yes
    wait_timeout: 300
  when: (dro_subscription.resources is defined) and (dro_subscription.resources| length == 1)

- name: "uninstall : Delete ibm-data-reporter-operator Subscription"
  kubernetes.core.k8s:
    state: absent
    api_version: operators.coreos.com/v1alpha1
    kind: Subscription
    name: ibm-data-reporter-operator
    namespace: redhat-marketplace
    wait: yes
    wait_timeout: 300
  when: (dro_subscription.resources is defined) and (dro_subscription.resources| length == 1)


# RMO

- name: Get ibm-metrics-operator Subscription
  kubernetes.core.k8s_info:
    api_version: operators.coreos.com/v1alpha1
    kind: Subscription
    namespace: redhat-marketplace
    label_selectors:
      - "instance = rmo"
  register: rmo_subscription


- name: "uninstall : Delete  redhat-marketplace-operator CSV"
  kubernetes.core.k8s:
    state: absent
    api_version: operators.coreos.com/v1alpha1
    kind: ClusterServiceVersion
    namespace: redhat-marketplace
    label_selectors:
      - "operators.coreos.com/redhat-marketplace-operator.redhat-marketplace"
    wait: yes
    wait_timeout: 300
  when: (rmo_subscription.resources is defined) and (rmo_subscription.resources| length == 1)

- name: "uninstall : Delete redhat-marketplace-operator Subscription"
  kubernetes.core.k8s:
    state: absent
    api_version: operators.coreos.com/v1alpha1
    kind: Subscription
    name: redhat-marketplace-operator
    namespace: redhat-marketplace
    wait: yes
    wait_timeout: 300
  when: (rmo_subscription.resources is defined) and (rmo_subscription.resources| length == 1)

# Delete secrets
- name: "uninstall : Delete the ibm-data-reporter-operator-api SA token secret"
  kubernetes.core.k8s:
    state: absent
    api_version: v1
    kind: Secret
    namespace: redhat-marketplace
    name: ibm-data-reporter-operator-api-token
