apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-data-reporter-operator
  namespace: redhat-marketplace
  labels:
    instance: dro
spec:
  channel: stable
  installPlanApproval: Automatic
  name: ibm-data-reporter-operator
  source: "{{ dro_source }}"
  sourceNamespace: "{{ dro_source_namespace }}"
  startingCSV: "{{ dro_csv }}"
