apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-metrics-operator
  namespace: redhat-marketplace
  labels:
    instance: imo
spec:
  channel: stable
  installPlanApproval: Automatic
  name: ibm-metrics-operator
  source: "{{ imo_source }}"
  sourceNamespace: "{{ imo_source_namespace }}"
